# Generated by Django 2.1.1 on 2019-11-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandboxtask',
            name='need_report',
            field=models.IntegerField(default=-1),
        ),
    ]
