# Generated by Django 2.1.1 on 2019-11-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_report', '0002_auto_20191119_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandboxreportlink',
            name='check_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sandboxreportlink',
            name='local_ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sandboxreportlink',
            name='local_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sandboxreportlink',
            name='module_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sandboxreportlink',
            name='monitor_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sandboxreportlink',
            name='pid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sandboxreportlink',
            name='run_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sandboxreportlink',
            name='script_res',
            field=models.TextField(blank=True),
        ),
    ]
