# Generated by Django 2.1.1 on 2019-11-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_report', '0004_auto_20191120_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SandboxReportLink',
        ),
        migrations.DeleteModel(
            name='SandboxReportVal',
        ),
    ]
