# Generated by Django 2.1.1 on 2019-11-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_report', '0005_auto_20191120_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxReportLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=-1)),
                ('mission_id', models.IntegerField(default=-1)),
                ('module_name', models.CharField(blank=True, max_length=50, null=True)),
                ('local_path', models.TextField(blank=True, null=True)),
                ('local_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('pid', models.CharField(blank=True, max_length=50, null=True)),
                ('run_time', models.CharField(blank=True, max_length=50, null=True)),
                ('check_time', models.CharField(blank=True, max_length=50, null=True)),
                ('monitor_link', models.TextField(blank=True, null=True)),
                ('script_res', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SandboxReportVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=-1)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_val', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
