# Generated by Django 2.1.1 on 2019-11-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_report', '0006_sandboxreportlink_sandboxreportval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SandboxReportLink',
        ),
        migrations.DeleteModel(
            name='SandboxReportVal',
        ),
        migrations.DeleteModel(
            name='SandboxTask',
        ),
    ]
