# Generated by Django 2.1.1 on 2019-11-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_report', '0009_auto_20191121_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxreportlink',
            name='errorlog',
            field=models.TextField(blank=True, null=True),
        ),
    ]
