# Generated by Django 2.1.1 on 2019-11-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_report', '0010_sandboxreportlink_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxreportlink',
            name='report_status',
            field=models.IntegerField(default=-1),
        ),
    ]
