# Generated by Django 2.1.1 on 2019-11-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_report', '0011_sandboxreportlink_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandboxreportlink',
            name='need_mail',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='sandboxreportlink',
            name='report_status',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
