# Generated by Django 2.1.1 on 2019-11-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_report', '0012_auto_20191121_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandboxreportval',
            name='item_val',
        ),
        migrations.AddField(
            model_name='sandboxreportval',
            name='item_avg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sandboxreportval',
            name='item_max',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sandboxreportval',
            name='item_min',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
