# Generated by Django 2.1.1 on 2019-11-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_report', '0013_auto_20191126_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxTaskSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_id', models.IntegerField(default=-1)),
                ('start_time', models.CharField(blank=True, max_length=50, null=True)),
                ('end_time', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(default=-1)),
            ],
        ),
    ]
