# Generated by Django 2.1.1 on 2019-12-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_report', '0014_sandboxtasksummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxreportlink',
            name='is_core',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
